[package]
name = "idola"
version = "0.1.0"
authors = ["Eidolon"]

[dependencies]
rand = "0.3.12"
byteorder = "0.4.2"
rustc-serialize = "0.3"
psocrypto = { path = "psocrypto" }
encoding = "0.2.32"
log = "0.3.4"
env_logger = "0.3.2"
typenum = "1.1.0"
toml = "0.1.24"
docopt = "0.6.78"

[[bin]]
name = "idola_patch"

[[bin]]
name = "idola_login"

[[bin]]
name = "idola_ship"

[[bin]]
name = "idola_data"

[[bin]]
name = "idola_monolith"
