[package]
name = "psodb_sqlite"
version = "0.1.0"
authors = ["Eidolon"]

[dependencies]
psodata = { path = "../psodata" }
psoserial = { path = "../psoserial" }
psodb_common = { path = "../psodb_common" }
rusqlite = { version = "0.12", features = ["bundled"] }
log = "0.3"
