[package]
name = "psodb_sqlite"
version = "0.1.0"
authors = ["Eidolon"]

[dependencies]
psodata = { path = "../psodata" }
psoserial = { path = "../psoserial" }
psodb_common = { path = "../psodb_common" }
rusqlite = "0.6.1"
log = "0.3"
