[package]
name = "psodata"
version = "0.1.0"
authors = ["Eidolon"]
description = "Structures and parsers for PSO-specific data formats."

[dependencies]
psoserial = { path = "../psoserial" }
byteorder = "0.4"
log = "0.3"
